
export const rodzajBadanConst = {
    SANITARNO_EPIDEMIOLOGICZNE: "SANITARNO_EPIDEMIOLOGICZNE",
    OKRESOWE: "OKRESOWE",
    WSTEPNE: "WSTEPNE",
    KONTROLNE: "KONTROLNE"
}

export const typWizytyConst = {
    MEDYCYNA_PRACY: "MEDYCYNA_PRACY",
    SPECJALISTYKA: "SPECJALISTYKA",
}
